### ISSUE TITLE
Possible memory leak in utils/queue.js

### ISSUE THREAD

**Issue by iamolivinius** [genkgo/ember-localforage-adapter#31]
Correct me if I'm wrong but I guess there is a memory leak in https://github.com/genkgo/ember-localforage-adapter/blob/master/addon/utils/queue.js

New operations are added to the queue but not removed after they resolve. This leads to an ever-growing queue array which shouldn't be the case for long living web apps.

**Comment by frederikbosch** [comment]
@iamolivinius That would be correct. This is not a elegant solution. As all records are saved to one localforage key, it must be done sequentially. Therefore I came up with this solution. Best thing we can do is solve the memory leak.

Second step might be think of storing the data into multiple keys (one per model). It will increase performance because it can be done async. Then we would also have one queue per model.

**Comment by frederikbosch** [comment]
Maybe, this is too simple, but it could already help.

```js
    self.queue[queueKey] = new Ember.RSVP.Promise(function(resolve, reject) {
      self.queue[queueKey - 1].then (function () {
        self.queue.splice(queueKey, 1);
        callback(resolve, reject);
      });
    });
```

**Comment by frederikbosch** [comment]
Note: there is no specific reason why we store data into one localforage key. This project originated from the `localstorage` adapter. It was their decision to design the adapter as such.

**Comment by frederikbosch** [comment]
@iamolivinius Could you try #32? At least Travis thinks it is alright.

**Comment by iamolivinius** [comment]
Looks good to me. Thanks for the quick response :+1:

**Comment by frederikbosch** [comment]
Merged. Thanks for the help. Will tag next week.
