### ISSUE TITLE
Compatibility with Ember Data 2.0

### ISSUE THREAD

**Issue by frederikbosch** [genkgo/ember-localforage-adapter#39]

**Comment by sebweaver** [comment]
Hello,

About that, ELA (Ember Local Forage) 1.13.1 is compatible with ED 2.0, except one test called `push` (the one I added previously). Unfortunately, this seems to be related to a side effect of a cleaning in ED 2.0.

I added a comment in the PR of ED (please see https://github.com/emberjs/data/pull/3345#diff-for-comment-38619627) without response for now. I think I should add an issue too, referring this specific comment in order to have a quicker answer.

**Comment by sebweaver** [comment]
Issue added: https://github.com/emberjs/data/issues/3736

**Comment by frederikbosch** [comment]
Fixed.
