### ISSUE TITLE
queryRecord issue

### ISSUE THREAD

**Issue by acerov** [genkgo/ember-localforage-adapter#57]
Hi,

It seems to me that in `_query: function`
instead of:
`if (singleMatch) {`
should be something like:
`if (singleMatch & results.length>0) {`

because othervise `queryRecord` works fine just if the first record is a match.
If you think this is ok, please update `ember-113-compat` branch also.

**Comment by frederikbosch** [comment]
@acerov Agreed, this is an issue. I wonder what the desired behaviour in when `queryRecord` has no results. Should the promise be rejected?

**Comment by sebweaver** [comment]
This is not an issue, this is the expected behavior.

Since `queryRecord` returns a promise and its purpose is to fetch one single record, this promise should be [rejected](https://github.com/genkgo/ember-localforage-adapter/blob/master/addon/adapters/localforage.js#L75-L77) when nothing matches. This is tested [here](https://github.com/genkgo/ember-localforage-adapter/blob/master/tests/integration/crud-test.js#L293-L302).

Private method `_query` returns:
- an array of records or an empty array, when called by `query`
- a single record or nothing (`undefined`), when called by `queryRecord`

There is a parallel with `findAll` and `findRecord` which behave the same way.

@acerov Adding the suggested test would mix things up between `query` and `queryRecord` because the latter could receive an unexpected empty array and would resolve its promise with the same result as `query`.

**Comment by frederikbosch** [comment]
@acerov Make sure you catch the rejected promise, probably in the `model` hook in the router. Please see below (ES6).

`model() {
  let promise = this.store.queryRecord('item', { property: 'value' });
  promise.catch(() => { doSomethingHere(); });
  return promise;
}`

**Comment by acerov** [comment]
I think we do not understand each other,
problem is that if any other than first record satisfy the criteria queryRecord does not work.
`(singleMatch) {` is tested in records loop and if singleMatch is true it exits in first run through that loop with first results[0], we did not have a chance to even test other records, it should run through the records loop until we have that first match and then return it
`if (singleMatch & results.length>0) {`
Sorry for my english but I hope I did explain well :)

**Comment by frederikbosch** [comment]
I think you are right.

**Comment by sebweaver** [comment]
Ok, I see your point. I did not understand that in you first comment.

**Comment by frederikbosch** [comment]
```js
if (singleMatch && isMatching) {
```

**Comment by frederikbosch** [comment]
That should fix it, right?

**Comment by sebweaver** [comment]
Not sufficient, you also have to handle the case when there's not match at all, otherwise `_query` will return an empty array in the end.

This new code should do the trick:

```javascript
  _query(records, query, singleMatch) {
    const results = singleMatch ? null : [];

    for (let id in records) {

      (...)

      if (isMatching) {
        if (singleMatch) {
          return record;
        }
        
        results.push(record);
      }
    }

    return results;
  },
```

Or, if you prefer not to return early (a matter of taste):

```javascript
  _query(records, query, singleMatch) {
    const results = singleMatch ? null : [];

    for (let id in records) {

      (...)

      if (isMatching) {
        if (singleMatch) {
          results = record;
        } else {
          results.push(record);
        }
      }
    }

    return results;
  },
```

@frederikbosch Actually this is more or less what I commited before you broke it [here](https://github.com/genkgo/ember-localforage-adapter/commit/2d116cff01c6956f4793fdf6400ea613e5a43ccc)! :stuck_out_tongue: :wink:

**Comment by acerov** [comment]
right to the point :smile: 
@sebweaver your first code block with early exit feels right to me

**Comment by frederikbosch** [comment]
I will add a tag today.

**Comment by sebweaver** [comment]
Travis failed on `ember-113-compat` (error related to Babel). Don't know why, and not enough time to investigate soon.

Master branch is ok.
